language: node_js
node:
  - 10.15.1
nvm:
  - 6.9.0
addons:
  ssh_known_hosts:
  - igather.sytes.net:1118
before_install:
  - openssl aes-256-cbc -K $encrypted_90b980805ab1_key -iv $encrypted_90b980805ab1_iv
    -in .travis/deploy_rsa.enc -out ./travis/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/id_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
install:
  - npm install
script:
  - npm test
deploy:
  provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  app: connecc-api
  run: npm start
  on:
    branch: master
