language: node_js
addons:
  ssh_known_hosts:
  - igather.sytes.net:1118
nvm:
- 6.9.0
node:
- 10.15.1
before_install:
- openssl aes-256-cbc -K $encrypted_61557196f501_key -iv $encrypted_61557196f501_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
install:
- npm install
script:
- npm test
deploy:
  provider: script
  skip_cleanup: true
  app: connecc-api
  run: npm start
  on:
    branch: master
